include $(THEOS)/makefiles/common.mk

FRAMEWORK_NAME = KBAppList
KBAppList_FILES = KBAppList.mm ALViewController.m ALAppCell.m ALHeaderView.m ALResultsTableController.m 
KBAppList_INSTALL_PATH = /Library/Frameworks

KBAppList_CFLAGS = -fobjc-arc
KBAppList_PRIVATE_FRAMEWORKS=Preferences
include $(THEOS_MAKE_PATH)/framework.mk
